- name: GitHub Action for pytest
  uses: cclauss/GitHub-Action-for-pytest@0.5.0
- name: Coveralls Python
  # You may pin to the exact commit or the version.
  # uses: AndreMiras/coveralls-python-action@f5fd5c309b39d01599fb92c72d4f7409ea78aec9
  uses: AndreMiras/coveralls-python-action@v20201129
